displayName=Nex Swedish Voiceover
author=Grindalf
support=https://github.com/mattiasen1/nex-swedish-voiceover
description=Plays audio when Nex uses overhead text
tags=nex,audio,boss,swedish
plugins=com.nex.NexPlugin
